version: "3.9"

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: finmon_staging
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1554ryw
      PGDATA: /var/postgresql/data/pgdata

  finmon:
    container_name: finmon
    build: .
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/finmon
      - /usr/src/finmon/node_modules
    ports:
      - 3000:3000
    restart: always
    command: npm run dev